### ISSUE TITLE
Link sbagliato agli issue di Github

### ISSUE THREAD

**Issue by LucaBlackDragon** [dotnet/dotnet-api-docs.it-it#1]
I link agli issue su Github delle pagine *italiane* conducono al repository dedicato alla lingua *francese*.

Ad esempio, nella [pagina dedicata alla classe `ConcurrentDictionary`](https://docs.microsoft.com/it-it/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netframework-4.7.2):

![net_docs_comments](https://user-images.githubusercontent.com/3714010/49142523-43054f00-f2f9-11e8-8199-71e2c0e0e702.PNG)

Il link "direttamente su Github" conduce [qui](https://github.com/dotnet/dotnet-api-docs.fr-fr/issues/new?title=&body=%0A%0A%5BImmetti%20qui%20i%20commenti%5D%0A%0A%0A---%0A%23%23%23%23%20Dettagli%20del%20documento%0A%0A%E2%9A%A0%20*Non%20modificare%20questa%20sezione.%20%C3%88%20necessaria%20per%20i%20collegamenti%20relativi%20ai%20problemi%20tra%20docs.microsoft.com%20%E2%9E%9F%20GitHub.*%0A%0A*%20ID%3A%20806c6485-9396-e6bf-2f8e-f27866115626%0A*%20Version%20Independent%20ID%3A%203e499bf3-fa82-0b82-5d85-84a0b3fe0515%0A*%20Content%3A%20%5BConcurrentDictionary%26lt%3BTKey%2CTValue%26gt%3B%20Class%20(System.Collections.Concurrent)%5D(https%3A%2F%2Fdocs.microsoft.com%2Fit-it%2Fdotnet%2Fapi%2Fsystem.collections.concurrent.concurrentdictionary-2%3Fview%3Dnetframework-4.7.2)%0A*%20Content%20Source%3A%20%5Bxml%2FSystem.Collections.Concurrent%2FConcurrentDictionary%602.xml%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdotnet-api-docs.it-it%2Fblob%2Flive%2Fxml%2FSystem.Collections.Concurrent%2FConcurrentDictionary%602.xml)%0A*%20Product%3A%20**dotnet-api**%0A*%20GitHub%20Login%3A%20%40dotnet-bot%0A*%20Microsoft%20Alias%3A%20**dotnetcontent**)

**Comment by CeciAc** [comment]
Salve, @LucaBlackDragon 

Grazie per i commenti e i suggerimenti inviati. 

Li stiamo attivamente esaminando e risponderemo a breve. 

Cordiali saluti, 
Il team internazionale Microsoft Docs

**Comment by CeciAc** [comment]
Hi @JasonCard 
Please, have a look at this issue. I tested it in other locales but it only repros in it-IT (forwarding to the fr-FR repository)

**Comment by JasonCard** [comment]
@LucaBlackDragon Thank you very much for reporting this issue and it's now fixed.
cc @CeciAc
