### ISSUE TITLE
Traduzione sbagliata

### ISSUE THREAD

**Issue by UgoMarchesini** [dotnet/dotnet-api-docs.it-it#3]
Nella sezione Commenti il testo : "Il HashSet<T> classe fornisce le operazioni di impostazione ad alte prestazioni. Un set è una raccolta che **contiene elementi duplicati**, e i cui elementi sono in nessun ordine particolare." dovrebbe dire "... **non contiene elementi duplicati** ...".

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6b66ab1a-35aa-1bba-388c-30d698c1f50c
* Version Independent ID: d7dde1b9-fd16-dd30-6622-a15836579a9c
* Content: [HashSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/it-it/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8#feedback)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs.it-it/blob/live/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* Technology: **system.collections**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @UgoMarchesini
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Salve, @UgoMarchesini
Grazie per i commenti e i suggerimenti inviati. 

Il nostro team linguistico ha esaminato e accettato i suggerimenti inviati. I suggerimenti sono stati implementati e pubblicati negli articoli aggiornati sul sito Docs nelle pagine seguenti https://docs.microsoft.com/it-it/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8

Il tuo contributo ai nostri articoli è molto apprezzato e ci auguriamo che vorrai continuare a inviarci i tuoi utili suggerimenti. 

Cordiali saluti, 
Il team internazionale Microsoft Docs
